table Cas12aTargets
"CRISPR Cas12a guides, genome wide (bed9 + extra; off-targets in external bgzip tab file)"
    (
    string  chrom;        "Reference sequence chromosome or scaffold"
    uint    chromStart;   "0-based start of the 27nt PAM+spacer site"
    uint    chromEnd;     "chromStart + 27"
    string  name;         "Guide ID (may be empty)"
    uint    score;        "Score 0-1000 (labeled on the details page by trackDb scoreLabel)"
    char[1] strand;       "+ or -"
    uint    thickStart;   "Start of protospacer (thick);"
    uint    thickEnd;     "End of protospacer (thick)"
    uint    itemRgb;      "Display color R,G,B"
    string  guideSeq;     "Guide sequence"
    string  pam;          "Protospacer Adjacent Motif (PAM)"
    string  unique_TTTV;               "Unique at TTTV PAMs"
    string  unique_TTTN;               "Unique at TTTN PAMs"
    string  TTTV_enCas12a_specificity; "EnCas12a specificity vs TTTV: percentile (score)"
    string  TTTN_enCas12a_specificity; "EnCas12a specificity vs TTTN: percentile (score)"
    string  TTTV_AsCas12a_specificity; "AsCas12a specificity vs TTTV: percentile (score)"
    string  TTTN_AsCas12a_specificity; "AsCas12a specificity vs TTTN: percentile (score)"
    string  ascas12a_deepcpf1_score;   "AsCas12a-DeepCpf1 efficiency: percentile (score)"
    string  enseq_deepcpf1_score;      "EnCas12a-DeepCpf1 efficiency: percentile (score)"
    string  deepcpf1_score;            "DeepCpf1 efficiency: percentile (score)"
    string  enpam_gb_score;            "EnPAM-GB efficiency: percentile (score)"
    string  _mouseOver;   "Hover label (mouseOver)"
    bigint  _offset;      "Uncompressed byte offset into crisprDetails.tab, or 0 if non-unique"
    )
