"""Unit + parity tests for crisprware.scorers.enseq_deepcpf1.

The 1,600-row golden CSV (copied from the Chen 2025 Code Ocean capsule) carries
a y_pred column generated by the upstream PyTorch model. Our TF2 port must
match it bit-for-bit (within tight tolerance for float32 nondeterminism) so
existing literature comparisons stay reproducible.
"""
from __future__ import annotations

import os
import sys

import numpy as np
import pandas as pd
import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from crisprware.scorers import enseq_deepcpf1

GOLDEN_CSV = os.path.join(
    REPO_ROOT, "tests", "test_data", "cas12a_scores", "chen_2025_enseq_golden.csv"
)
WEIGHTS = os.path.join(
    REPO_ROOT, "crisprware", "scorers", "weights", "chen_2025", "enseq_deepcpf1.npz"
)

weights_required = pytest.mark.skipif(
    not os.path.exists(WEIGHTS),
    reason=f"missing {WEIGHTS} -- run `python tools/extract_chen_2025_weights.py` first",
)


def test_is_valid_seq_31():
    assert enseq_deepcpf1.is_valid_seq("A" * 31, length=31)
    assert not enseq_deepcpf1.is_valid_seq("A" * 30, length=31)
    assert not enseq_deepcpf1.is_valid_seq("N" + "A" * 30, length=31)


def test_is_valid_seq_34_default():
    assert enseq_deepcpf1.is_valid_seq("A" * 34)
    assert not enseq_deepcpf1.is_valid_seq("A" * 33)


def test_context_34_to_31_drops_first_char():
    ctx = "ACATTTTACTTTTTCAAAATTGTTTTCATGCTAA"
    chen = enseq_deepcpf1.context_34_to_31(ctx)
    assert len(chen) == 31
    assert chen == ctx[1:32]
    # Sanity: PAM should still be at positions 3-6 (Chen convention)
    assert chen[3:7] == "TTTA"


def test_one_hot_encoding_atcg_order():
    """A=0, T=1, C=2, G=3 (DIFFERENT from DeepCpf1's A=0, C=1, G=2, T=3)."""
    arr = enseq_deepcpf1.one_hot_encode_31(["ATCG" * 7 + "ATC"])
    assert arr.shape == (1, 31, 4)
    assert arr.dtype == np.float32
    # Position 0: A -> channel 0
    np.testing.assert_array_equal(arr[0, 0, :], [1, 0, 0, 0])
    # Position 1: T -> channel 1
    np.testing.assert_array_equal(arr[0, 1, :], [0, 1, 0, 0])
    # Position 2: C -> channel 2
    np.testing.assert_array_equal(arr[0, 2, :], [0, 0, 1, 0])
    # Position 3: G -> channel 3
    np.testing.assert_array_equal(arr[0, 3, :], [0, 0, 0, 1])


@pytest.fixture(scope="module")
def model():
    pytest.importorskip("tensorflow")
    if not os.path.exists(WEIGHTS):
        pytest.skip(f"missing {WEIGHTS}")
    return enseq_deepcpf1.load_model(WEIGHTS)


@weights_required
def test_capsule_dataset_seq_matches_seq34_slice():
    """seq34[1:32] must equal seq across the capsule's training/eval rows."""
    capsule_csv = os.path.join(
        REPO_ROOT, "capsule-9398276", "data", "EnDeepCpf1", "dataset", "HEK_HCT_plasmid.csv"
    )
    if not os.path.exists(capsule_csv):
        pytest.skip(f"missing capsule fixture at {capsule_csv}")
    df = pd.read_csv(capsule_csv)
    for _, row in df.head(50).iterrows():
        assert row["seq34"][1:32] == row["seq"], row.to_dict()


def test_model_layer_weights_loaded(model):
    """All five layers should have non-zero weights post-load."""
    for layer_name in ("conv1", "conv2", "fc1", "fc2", "out"):
        layer = model.get_layer(layer_name)
        w, b = layer.get_weights()
        assert w.size > 0 and np.any(w != 0), layer_name
        assert b.size > 0


def test_predict_matches_golden_top10(model):
    """Top 10 rows of the capsule's published predictions must match within 1e-4."""
    df = pd.read_csv(GOLDEN_CSV).head(10)
    seqs_31 = df["seq"].tolist()
    golden = df["y_pred"].astype(float).to_numpy()
    scored = np.array(
        enseq_deepcpf1.predict(seqs_31, model=model, input_length=31), dtype=float
    )
    max_diff = float(np.max(np.abs(scored - golden)))
    assert max_diff < 1e-4, (
        f"enseq-DeepCpf1 port diverges from golden by {max_diff} on top-10. "
        f"scored={scored.tolist()}, golden={golden.tolist()}"
    )


def test_predict_spearman_full_golden(model):
    """Full 1,600-row golden -- Spearman ≥ 0.9999, mean abs diff ≤ 1e-4."""
    from scipy.stats import spearmanr

    df = pd.read_csv(GOLDEN_CSV)
    seqs_31 = df["seq"].tolist()
    golden = df["y_pred"].astype(float).to_numpy()
    scored = np.array(
        enseq_deepcpf1.predict(seqs_31, model=model, input_length=31), dtype=float
    )
    rho, _ = spearmanr(scored, golden)
    mean_abs = float(np.mean(np.abs(scored - golden)))
    max_abs = float(np.max(np.abs(scored - golden)))
    assert rho >= 0.9999, f"Spearman {rho:.6f} below 0.9999"
    assert mean_abs <= 1e-4, f"mean abs diff {mean_abs} > 1e-4"
    assert max_abs <= 1e-3, f"max abs diff {max_abs} > 1e-3"


def test_predict_via_34nt_context_matches_31nt(model):
    """Feeding 34-nt context should give identical predictions to feeding seq34[1:32]."""
    capsule_csv = os.path.join(
        REPO_ROOT, "capsule-9398276", "data", "EnDeepCpf1", "dataset", "HEK_HCT_plasmid.csv"
    )
    if not os.path.exists(capsule_csv):
        pytest.skip(f"missing capsule fixture at {capsule_csv}")
    df = pd.read_csv(capsule_csv).head(20)
    p31 = np.array(enseq_deepcpf1.predict(df["seq"].tolist(),  model=model, input_length=31))
    p34 = np.array(enseq_deepcpf1.predict(df["seq34"].tolist(), model=model, input_length=34))
    np.testing.assert_allclose(p31, p34, atol=1e-6)


def test_predict_invalid_seq_returns_nan(model):
    out = enseq_deepcpf1.predict(["A" * 33, "A" * 34], model=model)
    assert np.isnan(out[0])
    assert not np.isnan(out[1])
