name: crisprware
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - biopython>=1.8
  - pybedtools>=0.9
  - pybigwig
  - pandas
  - numpy
  - pip
  - pip:
    - lightgbm==3.3.5
    - rs3>=0.0.15
